name: rock
recipe: drupal9
config:
  webroot: web
  php: "7.4"
services:
  appserver:
    run:
      - composer install
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://rock.lndo.site"
